#!/bin/bash

# Create and activate cpac (wrapper) virtual environment
python -m venv wrapper
source wrapper/bin/activate
pip install --upgrade pip
pip install -r cpac-requirements.txt
python -m ipykernel install --user --name wrapper --display-name "cpac (commandline wrapper)"
deactivate

# Create and activate C-PAC (core) virtual environment
python -m venv core
source core/bin/activate
pip install --upgrade pip
pip install nipype==1.8.6 numpy==1.25.1 pyyaml setuptools voluptuous wheel
pip install -r C-PAC-requirements.txt
python -m ipykernel install --user --name core --display-name "C-PAC (core software)"
deactivate
