# Copyright (C) 2022  C-PAC Developers
# This file is part of C-PAC_tutorials.
# C-PAC_tutorials is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# C-PAC_tutorials is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along with C-PAC. If not, see <https://www.gnu.org/licenses/>.
name: Rebuild nightly docs

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  rebuild-user-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Build nightly documentation
        uses: shnizzedy/github-action-trigger-circleci@v1.1.1
        with:
          branch: source
          job: "build-nightly"
          org: FCP-INDI
          repo: fcp-indi.github.io
          token: ${{ secrets.CIRCLE_CI_TOKEN }}
